### ISSUE TITLE
Облегчение установки

### ISSUE THREAD

**Issue by foxhable** [Catalyst-42/mineflyaer-digger-bot#1]
Ты можешь добавить файл package.json с Dependencies, которые нужны для работы бота, mineflayer например. Тогда установка сведется к том, что нужно скачать файлы и прописать "npm install". В этом случае нпм берет из package.json зависимости и устанавливает их. Не спутай с devDependencies, это зависимости, которые нужны только для разработки, но не для работы проекта.

**Comment by Catalyst-42** [comment]
Отличная идея, спасибо
