### ISSUE TITLE
Store items in a box

### ISSUE THREAD

**Issue by Katzengott** [Catalyst-42/mineflyaer-digger-bot#2]
If the bot wants to store the items in the box, it disconnects and this error occurs:   
matching: blocks.map(name => mcData.blocksByName[name].id),
                                          ^

TypeError: Cannot read properties of undefined (reading 'blocksByName')

**Comment by Catalyst-42** [comment]
What version of Minecraft and Mineflayer and Node do you use?

If it is 16.x - 1.17.1 then everything should work fine with `--unhandled-rejections=none` on last Node versions
`node --unhandled-rejections=none index.js <host> <port> <name>`

I also tried to reproduce the error, but could not, can you also describe the way to get the error

**Comment by Katzengott** [comment]
It may be that I have simply placed the boxes incorrectly can you send a better plan

**Comment by Catalyst-42** [comment]
This should not affect the error if the chest is located within 8 blocks of the bot and can be opened

**Comment by Katzengott** [comment]
Ok then it's not the problem

**Comment by Catalyst-42** [comment]
So, I edited code to 1.17 mcData base, I hope this helps

**Comment by Katzengott** [comment]
Thank you I will test it

**Comment by Katzengott** [comment]
he still can't find the chests

**Comment by Catalyst-42** [comment]
Oh, then please write on what version of Minecraft and Mineflayer and Node you run the bot and describe the path to reproduce the error

**Comment by Katzengott** [comment]
I use the latest node.js version and the latest Mineflayer version. My Minecraft version is the 1.16.5. Here is a picture of how I arranged the chests
![Inkedchest](https://user-images.githubusercontent.com/78551650/146190845-fbee835e-f844-4d5e-abb2-c43d596417db.jpg)

**Comment by Catalyst-42** [comment]
Caught it, try running the corrected code, should work. Older versions seem to detect the mcData module differently

**Comment by Katzengott** [comment]
Finally it worked. Thank you for taking so much time. Would this script also go in 1.17

**Comment by Catalyst-42** [comment]
Thank you for using the bot! Also the bot should work stable on 1.17 versions of Minecraft
