### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by ParussMan** [Catalyst-42/mineflyaer-digger-bot#5]
Не уверен, проблема ли в самом боте, но учитывая отсутствие активности здесь и в целом пропажу автора, решил отписаться, может автор увидит и объяснит в чем проблема.

![изображение](https://user-images.githubusercontent.com/79791478/203855202-517c1646-eaef-4474-a96e-165f6c6aa9e7.png)

Выдает эту ошибку при запуске бота, перепробовал всё, но увы.

**Comment by Catalyst-42** [comment]
Не помню, чтобы в файлах бота был `bot2.js`, но сейчас mineflayer испытывает гигантские проблемы сам по себе, так что версии после 1.18 (чистого 1.18.0) могут вызывать случайные ошибки от запуска к запуску. Если я правильно понимаю, то ошибка кроется в файле `bot2.js` на 386 строчке

**Comment by Catalyst-42** [comment]
Если это просто изменённый мой `index.js`, может быть это конфликт имён функций, попробуйте переименовать везде `freeItems` во что-нибудь другое

**Comment by ParussMan** [comment]
Это был твой измененный, ага, только с отличием в свойствах самого бота (ник и подключение), всё остальное было идентичным.
> сейчас mineflayer испытывает гигантские проблемы сам по себе, так что версии после 1.18 (чистого 1.18.0)
Об этом я в курсе, т.к. листал по другим гитхабам в поисках решения. Только вот я сам пытался запустить его на 1.16.5, так что вроде проблема не в этом.

Вообще, то, что изначально вызывало эту проблему оказался autoEat, который после полного удаления из кода позволил запустить бота. Правда, после этого он на моменте начала копания начал выдавать ошибки и краш сначала в функции просчёта воды и лавы, а потом я уже сбился со счету и забил на всё это. Извиняюсь, что отнял время.
